from enum import Enum


class EvidenceType(str, Enum):
    COLUMN_MISSINGNESS = "COLUMN_MISSINGNESS" 
    ROWS_MISSINGNESS =  "ROWS_MISSINGNESS" 
    MISSINGNESS_DISTRIBUTION = "MISSINGNESS_DISTRIBUTION"
      