from enum import Enum


class EvidenceType(str, Enum):
    COLUMN_MISSINGNESS = "COLUMN_MISSINGNESS" 
    ROWS_MISSINGNESS =  "ROWS_MISSINGNESS" 
    MISSINGNESS_DISTRIBUTION = "MISSINGNESS_DISTRIBUTION"
    DATA_PROFILE_CHECK = "DATA_PROFILE_CHECK"
    STATISTICAL_TEST = "STATISTICAL_TEST"
    DISTRIBUTION_COMPARISON = "DISTRIBUTION_COMPARISON"
      