from enum import Enum

class FindingType (str, Enum): 
    #Missing value analysis finding types 
    ALL_MISSING_COLUMN  = "ALL_MISSING_COLUMN"
    HIGH_MISSING_VALUE_RATE = "HIGH_MISSING_VALUE_RATE"
    MODERATE_MISSING_VALUE_RATE = "MODERATE_MISSING_VALUE_RATE" 
    HIGH_ROW_MISSING_VALUE_RATE = "HIGH_ROW_MISSING_VALUE_RATE"
    VALUE_MISSINGNESS_MECHANISM =  "VALUE_MISSINGNESS_MECHANISM"
    MISSING_CLUSTERED_IN_SEGMENT = "MISSING_CLUSTERED_IN_SEGMENT " 
    CORRELATED_VALUE_MISSINGNESS =  "CORRELATED_MISSINGNESS"
    VALUE_MISSINGNESS_IMPACT = "VALUE_MISSINGNESS_IMPACT"
    INFORMATION_LOSS_DUE_TO_MISSING_VALUES =  "INFORMATION_LOSS_DUE_TO_MISSING_VALUES"