from enum import Enum

class InvestigationEngine (str, Enum):
    DATA_INVESTIGATION_ENGINE = 'DATA_INVESTIGATION_ENGINE'
    MODEL_INVESTIGATION_ENGINE = 'MODEL_INVESTIGATION_ENGINE'
    SYSTEM_INVESTIGATION_ENGINE = "SYSTEM_INVESTIGATION_ENGINE" 