from typing import Protocol


class ObservationStore(Protocol):
    def insert(self, observation): ...
    def fetch_by_type(self, observation_type: str): ...


class SignalStore(Protocol):
    def insert(self, signal): ...
    def fetch_by_type(self, signal_type: str): ...


class InvestigationStore(Protocol):
    def insert(self, investigation): ...
    def fetch(self, investigation_id: str): ...